---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: client-56-amazonlinux-2
          suite: client-56-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-amazon-linux
          suite: client-56-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-centos-6
          suite: client-56-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-centos-7
          suite: client-56-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-debian-8
          suite: client-56-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-debian-9
          suite: client-56-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-opensuse-leap-15
          suite: client-56-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-ubuntu-1604
          suite: client-56-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-56-ubuntu-1804
          suite: client-56-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-amazonlinux-2
          suite: client-57-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-amazon-linux
          suite: client-57-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-centos-6
          suite: client-57-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-centos-7
          suite: client-57-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-debian-8
          suite: client-57-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-debian-9
          suite: client-57-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-opensuse-leap-15
          suite: client-57-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-ubuntu-1604
          suite: client-57-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: client-57-ubuntu-1804
          suite: client-57-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-amazonlinux-2
          suite: server-56-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-amazon-linux
          suite: server-56-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-centos-6
          suite: server-56-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-centos-7
          suite: server-56-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-debian-8
          suite: server-56-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-debian-9
          suite: server-56-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-opensuse-leap-15
          suite: server-56-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-ubuntu-1604
          suite: server-56-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-56-ubuntu-1804
          suite: server-56-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-amazonlinux-2
          suite: server-57-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-amazon-linux
          suite: server-57-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-centos-6
          suite: server-57-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-centos-7
          suite: server-57-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-debian-8
          suite: server-57-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-debian-9
          suite: server-57-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-opensuse-leap-15
          suite: server-57-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-ubuntu-1604
          suite: server-57-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-57-ubuntu-1804
          suite: server-57-ubuntu-1804
          requires: *lint_and_unit
